import Config.Koneksi;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author firza
 */
public class DataMapel extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    private final Connection conn;
    public DataMapel() {
        initComponents();
        
        conn = Koneksi.getConnection();
        setTabelModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmain = new javax.swing.JPanel();
        datamapel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatamapel = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        btnubah = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tambahdatamapel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtidmapel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbmapel = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        panelmain.setBackground(new java.awt.Color(255, 255, 255));
        panelmain.setLayout(new java.awt.CardLayout());

        datamapel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Master Data > Data Mata Pelajaran ");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tv-20.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data Mata Pelajaran ");

        tbldatamapel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbldatamapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldatamapelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldatamapel);

        btntambah.setBackground(new java.awt.Color(102, 102, 255));
        btntambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 0, 0));
        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(255, 153, 0));
        btnbatal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 102, 102));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });

        btnubah.setBackground(new java.awt.Color(102, 102, 255));
        btnubah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-20.png"))); // NOI18N

        javax.swing.GroupLayout datamapelLayout = new javax.swing.GroupLayout(datamapel);
        datamapel.setLayout(datamapelLayout);
        datamapelLayout.setHorizontalGroup(
            datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datamapelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, datamapelLayout.createSequentialGroup()
                        .addGroup(datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(datamapelLayout.createSequentialGroup()
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                        .addGroup(datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datamapelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datamapelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        datamapelLayout.setVerticalGroup(
            datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datamapelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelmain.add(datamapel, "card2");

        tambahdatamapel.setBackground(new java.awt.Color(255, 255, 255));
        tambahdatamapel.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Master Data > Data Mata Pelajaran > Tambah Data");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tv-20.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Tambah Data Mata Pelajaran");

        btnsimpan.setBackground(new java.awt.Color(102, 102, 255));
        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(255, 153, 0));
        btncancel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btncancel.setText("BATAL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Id_Mapel");

        txtidmapel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtidmapel.setForeground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Mata Pelajaran");

        cbmapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Item--", "Akuntansi Keuangan", "Bahasa Inggris", "Bahasa Indonesia", "Matematika", "PPKN", "Kewirausahaan", "Komputer Akuntansi", "Ak Pemerintah", "Ak Manufaktur", "Pajak", "Pai", " " }));

        javax.swing.GroupLayout tambahdatamapelLayout = new javax.swing.GroupLayout(tambahdatamapel);
        tambahdatamapel.setLayout(tambahdatamapelLayout);
        tambahdatamapelLayout.setHorizontalGroup(
            tambahdatamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdatamapelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tambahdatamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahdatamapelLayout.createSequentialGroup()
                        .addGroup(tambahdatamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahdatamapelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addGroup(tambahdatamapelLayout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(tambahdatamapelLayout.createSequentialGroup()
                        .addGroup(tambahdatamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtidmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambahdatamapelLayout.createSequentialGroup()
                        .addGroup(tambahdatamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cbmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        tambahdatamapelLayout.setVerticalGroup(
            tambahdatamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdatamapelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tambahdatamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(tambahdatamapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(475, Short.MAX_VALUE))
        );

        panelmain.add(tambahdatamapel, "card2");

        add(panelmain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(btnsimpan.getText().equals("TAMBAH")){
            btnsimpan.setText("SIMPAN");
        }
        else if(btnsimpan.getText().equals("SIMPAN")){
            insertData();
        }
        else if(btnsimpan.getText().equals("PERBARUI")){
            updateData();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        panelmain.removeAll();
        panelmain.add(tambahdatamapel);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
        searchData();
    }//GEN-LAST:event_txtsearchKeyTyped

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        updateData();
        
        if(btnubah.getText().equals("UBAH")){
            dataTabel();
            btnsimpan.setText("PERBARUI");
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void tbldatamapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldatamapelMouseClicked
        if(btntambah.getText().equals("TAMBAH")){
            btnubah.setVisible(true);
            btnhapus.setVisible(true);
            btnbatal.setVisible(true);
        }
    }//GEN-LAST:event_tbldatamapelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbmapel;
    private javax.swing.JPanel datamapel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPanel tambahdatamapel;
    private javax.swing.JTable tbldatamapel;
    private javax.swing.JTextField txtidmapel;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        getData((DefaultTableModel) tbldatamapel.getModel());
        }
    
    private void showPanel(){
        panelmain.removeAll();
        panelmain.add(new DataMapel());
        panelmain.repaint();
        panelmain.revalidate();
    }
    
    private void resetForm() {
        txtidmapel.setText("");
        cbmapel.setSelectedItem(0);
    }

    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tbldatamapel.getModel();
        model.addColumn("Id Mata Pelajaran");
        model.addColumn("Mata Pelajaran");
    }
    
    private void getData(DefaultTableModel model){
        model.setRowCount(0);
        
        try {
            String sql = "Select *from Mapel";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                
                while (rs.next()){
                    String idmapel = rs.getString("Id_Mapel");
                    String mapel = rs.getString("Nama_Mapel");
                    
                    Object[] rowData = {idmapel,mapel};
                    model.addRow(rowData);
                }
            }
        }catch (Exception e) {
            Logger.getLogger(DataMapel.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void insertData() {
        String idmapel = txtidmapel.getText();
        String mapel = cbmapel.getSelectedItem().toString();
        
        if(idmapel.isEmpty()||mapel.isEmpty()){
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !","Validasi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "insert into Mapel(Id_Mapel,Nama_Mapel) values (?,?)";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, idmapel);
                st.setString(2, mapel);
                
                int rowInserted = st.executeUpdate();
                if(rowInserted > 0) {
                    JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (Exception e){
            Logger.getLogger(DataMapel.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void dataTabel() {
        datamapel.setVisible(false);
        tambahdatamapel.setVisible(true);
        
        int row = tbldatamapel.getSelectedRow();
        jLabel6.setText("Perbarui Data Mapel");
        jLabel4.setText("Master Data > Data Mata Pelajaran > Perbarui Data");
        
        txtidmapel.setText(tbldatamapel.getValueAt(row,0).toString());
        cbmapel.setSelectedItem (tbldatamapel.getValueAt(row,1).toString());
    }
    
    private void updateData() {
    String idmapel = txtidmapel.getText();
    String mapel = cbmapel.getSelectedItem().toString();

    if(idmapel.isEmpty() || mapel.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !","Validasi",JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        String sql = "UPDATE Mapel SET Nama_Mapel = ? WHERE Id_Mapel = ?";
        try(PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, mapel);
            st.setString(2, idmapel);

            int rowUpdated = st.executeUpdate();
            if(rowUpdated > 0) {
                JOptionPane.showMessageDialog(this,"Data Berhasil Diperbarui");
                resetForm();
                loadData();
                showPanel();
            }
        }
    } catch (Exception e) {
        Logger.getLogger(DataMapel.class.getName()).log(Level.SEVERE, null, e);
    }
}

    private void deleteData() {
        int selectedRow = tbldatamapel.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda Yakin Ingin Menghapus Data Ini?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            String idmapel = tbldatamapel.getValueAt(selectedRow, 0).toString();
            try {
                String sql = "delete from Mapel where Id_Mapel=?";
                try(PreparedStatement st = conn.prepareStatement(sql)){
                    st.setString(1, idmapel);
                    int rowDeleted = st.executeUpdate();
                    if(rowDeleted > 0) {
                        JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus");
                    } else{
                        JOptionPane.showMessageDialog(this,"Data Gagal Dihapus");
                    }
                } 
            } catch (Exception e){
            Logger.getLogger(DataMapel.class.getName()).log(Level.SEVERE,null, e);
            }
        }
        resetForm();
        loadData();
        showPanel();
    }

    private void searchData() {
        String kataKunci = txtsearch.getText();
        
        DefaultTableModel model = (DefaultTableModel) tbldatamapel.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "Select *from Mapel where Id_Mapel LIKE ? OR Nama_Mapel LIKE ? ";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, "%" + kataKunci + "%");
                st.setString(2, "%" + kataKunci + "%");
                ResultSet rs = st.executeQuery();
                
                while (rs.next()){
                    String idmapel = rs.getString("Id_Mapel");
                    String mapel = rs.getString("Nama_Mapel");
                    
                    Object[] rowData = {idmapel,mapel};
                    model.addRow(rowData);
                }
            }
        }catch (Exception e) {
            Logger.getLogger(DataMapel.class.getName()).log(Level.SEVERE,null, e);
        }
    }
}
