import Config.Koneksi;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author firza
 */
public class DataSiswa extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    private final Connection conn;
    public DataSiswa() {
        initComponents();
        
        conn = Koneksi.getConnection();
        setTabelModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJK = new javax.swing.ButtonGroup();
        panelmain = new javax.swing.JPanel();
        datasiswa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatasiswa = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        btnubah = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tambahdatasiswa = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtnis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbjurusan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbkelas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtnotelp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        txtttl = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelmain.setBackground(new java.awt.Color(255, 255, 255));
        panelmain.setLayout(new java.awt.CardLayout());

        datasiswa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Master Data > Data Siswa ");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tv-20.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data Siswa ");

        tbldatasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbldatasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldatasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldatasiswa);

        btntambah.setBackground(new java.awt.Color(102, 102, 255));
        btntambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 0, 0));
        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(255, 153, 0));
        btnbatal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 102, 102));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });

        btnubah.setBackground(new java.awt.Color(102, 102, 255));
        btnubah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-20.png"))); // NOI18N

        javax.swing.GroupLayout datasiswaLayout = new javax.swing.GroupLayout(datasiswa);
        datasiswa.setLayout(datasiswaLayout);
        datasiswaLayout.setHorizontalGroup(
            datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, datasiswaLayout.createSequentialGroup()
                        .addGroup(datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(datasiswaLayout.createSequentialGroup()
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                        .addGroup(datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datasiswaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datasiswaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        datasiswaLayout.setVerticalGroup(
            datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelmain.add(datasiswa, "card2");

        tambahdatasiswa.setBackground(new java.awt.Color(255, 255, 255));
        tambahdatasiswa.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Master Data > Data Siswa > Tambah Data");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tv-20.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Tambah Data Siswa ");

        btnsimpan.setBackground(new java.awt.Color(102, 102, 255));
        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(255, 153, 0));
        btncancel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btncancel.setText("BATAL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("NIS");

        txtnis.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnis.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nama Siswa");

        txtnama.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(51, 51, 51));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Jurusan");

        cbjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Item--", "Akuntansi", "Teknologi Komputer Jaringan", "Otomatisasi dan Tata Kelola Perkantoran" }));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Kelas");

        cbkelas.setForeground(new java.awt.Color(51, 51, 51));
        cbkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Item--", "X", "XI", "XII" }));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("No Telp");

        txtnotelp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnotelp.setForeground(new java.awt.Color(51, 51, 51));
        txtnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotelpActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Email");

        txtemail.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtemail.setForeground(new java.awt.Color(51, 51, 51));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Jenis Kelamin");

        rbJK.add(rblaki);
        rblaki.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        rblaki.setForeground(new java.awt.Color(51, 51, 51));
        rblaki.setText("Laki-laki");

        rbJK.add(rbperempuan);
        rbperempuan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        rbperempuan.setForeground(new java.awt.Color(51, 51, 51));
        rbperempuan.setText("Perempuan");
        rbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbperempuanActionPerformed(evt);
            }
        });

        txtttl.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtttl.setForeground(new java.awt.Color(51, 51, 51));
        txtttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtttlActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Tempat, Tanggal Lahir");

        javax.swing.GroupLayout tambahdatasiswaLayout = new javax.swing.GroupLayout(tambahdatasiswa);
        tambahdatasiswa.setLayout(tambahdatasiswaLayout);
        tambahdatasiswaLayout.setHorizontalGroup(
            tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdatasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahdatasiswaLayout.createSequentialGroup()
                        .addGroup(tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahdatasiswaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 614, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addGroup(tambahdatasiswaLayout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(tambahdatasiswaLayout.createSequentialGroup()
                        .addGroup(tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambahdatasiswaLayout.createSequentialGroup()
                        .addGroup(tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahdatasiswaLayout.createSequentialGroup()
                                .addComponent(rblaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbperempuan))
                            .addComponent(jLabel13)
                            .addGroup(tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addComponent(jLabel9)
                                .addComponent(cbjurusan, 0, 443, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)
                                .addComponent(txtnama)
                                .addComponent(cbkelas, 0, 443, Short.MAX_VALUE)
                                .addComponent(txtttl)
                                .addComponent(txtnotelp)
                                .addComponent(txtemail)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        tambahdatasiswaLayout.setVerticalGroup(
            tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdatasiswaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtttl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahdatasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rblaki)
                    .addComponent(rbperempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        panelmain.add(tambahdatasiswa, "card2");

        add(panelmain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(btnsimpan.getText().equals("TAMBAH")){
            btnsimpan.setText("SIMPAN");
        }
        else if(btnsimpan.getText().equals("SIMPAN")){
            insertData();
        }
        else if(btnsimpan.getText().equals("PERBARUI")){
            updateData();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        panelmain.removeAll();
        panelmain.add(tambahdatasiswa);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotelpActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void rbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbperempuanActionPerformed

    private void txtttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtttlActionPerformed

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
        searchData();
    }//GEN-LAST:event_txtsearchKeyTyped

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        updateData();
        
        if(btnubah.getText().equals("UBAH")){
            dataTabel();
            btnsimpan.setText("PERBARUI");
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void tbldatasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldatasiswaMouseClicked
        if(btntambah.getText().equals("TAMBAH")){
            btnubah.setVisible(true);
            btnhapus.setVisible(true);
            btnbatal.setVisible(true);
        }
    }//GEN-LAST:event_tbldatasiswaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbjurusan;
    private javax.swing.JComboBox<String> cbkelas;
    private javax.swing.JPanel datasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelmain;
    private javax.swing.ButtonGroup rbJK;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JPanel tambahdatasiswa;
    private javax.swing.JTable tbldatasiswa;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtttl;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        getData((DefaultTableModel) tbldatasiswa.getModel());
        }
    
    private void showPanel(){
        panelmain.removeAll();
        panelmain.add(new DataSiswa());
        panelmain.repaint();
        panelmain.revalidate();
    }
    
    private void resetForm() {
        txtnis.setText("");
        txtnama.setText("");
        txtttl.setText("");
        rbJK.clearSelection();
        txtnotelp.setText("");
        txtemail.setText("");
        cbjurusan.setSelectedItem(0);
        cbkelas.setSelectedItem(0);
    }

    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tbldatasiswa.getModel();
        model.addColumn("NIS");
        model.addColumn("Nama Siswa");
        model.addColumn("Tempat, Tanggal Lahir");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No Telp");
        model.addColumn("Email");
        model.addColumn("Jurusan");
        model.addColumn("Kelas");
    }
    
    private void getData(DefaultTableModel model){
        model.setRowCount(0);
        
        try {
            String sql = "Select *from DataSiswa";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                
                while (rs.next()){
                    String nis = rs.getString("NIS");
                    String namasiswa = rs.getString("Nama_Siswa");
                    String ttl = rs.getString("Tempat_Tanggal_Lahir");
                    String jeniskelamin = rs.getString("Jenis_Kelamin");
                    String notelp = rs.getString("No_Telp");
                    String email = rs.getString("Email");
                    String jurusan = rs.getString("Jurusan");
                    String kelas = rs.getString("Kelas");
                    
                    Object[] rowData = {nis,namasiswa,ttl,jeniskelamin,notelp,email,jurusan,kelas};
                    model.addRow(rowData);
                }
            }
        }catch (Exception e) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void insertData() {
        String nis = txtnis.getText();
        String namasiswa = txtnama.getText();
        String ttl = txtttl.getText();
        String jeniskelamin;
            if(rblaki.isSelected()){
                
                jeniskelamin = rblaki.getText();
            } else if(rbperempuan.isSelected()){
                jeniskelamin = rbperempuan.getText();
            } else {
                jeniskelamin = "";
            }
        String notelp = txtnotelp.getText();
        String email = txtemail.getText();
        String jurusan = cbjurusan.getSelectedItem().toString();
        String kelas = cbkelas.getSelectedItem().toString();
        
        if(nis.isEmpty()||namasiswa.isEmpty()||ttl.isEmpty()||jeniskelamin.isEmpty()||notelp.isEmpty()||email.isEmpty()||jurusan.isEmpty()||kelas.isEmpty()){
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !","Validasi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "insert into DataSiswa(NIS,Nama_Siswa,Tempat_Tanggal_Lahir,Jenis_Kelamin,No_Telp,Email,Jurusan,Kelas) values (?,?,?,?,?,?,?,?)";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, nis);
                st.setString(2, namasiswa);
                st.setString(3, ttl);
                st.setString(4, jeniskelamin);
                st.setString(5, notelp);
                st.setString(6, email);
                st.setString(7, jurusan);
                st.setString(8, kelas);
                
                int rowInserted = st.executeUpdate();
                if(rowInserted > 0) {
                    JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (Exception e){
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void dataTabel() {
        datasiswa.setVisible(false);
        tambahdatasiswa.setVisible(true);
        
        int row = tbldatasiswa.getSelectedRow();
        jLabel6.setText("Perbarui Data Siswa");
        jLabel4.setText("Master Data > Data Siswa > Perbarui Data");
        
        txtnis.setText(tbldatasiswa.getValueAt(row,0).toString());
        txtnama.setText(tbldatasiswa.getValueAt(row,1).toString());
        txtttl.setText(tbldatasiswa.getValueAt(row,2).toString());
        String jeniskelamin = tbldatasiswa.getValueAt(row,3).toString();
            if(jeniskelamin.equals("Laki-laki")){
                rblaki.setSelected(true);
            } else if(jeniskelamin.equals("Perempuan")){
                rbperempuan.setSelected(true);
            }
        txtnotelp.setText(tbldatasiswa.getValueAt(row,4).toString());
        txtemail.setText(tbldatasiswa.getValueAt(row,5).toString());
        cbjurusan.setSelectedItem (tbldatasiswa.getValueAt(row,6).toString());
        cbkelas.setSelectedItem (tbldatasiswa.getValueAt(row,7).toString());
    }
    
    private void updateData() {
        String nis = txtnis.getText();
        String namasiswa = txtnama.getText();
        String ttl = txtttl.getText();
        String jeniskelamin;
            if(rblaki.isSelected()){
                
                jeniskelamin = rblaki.getText();
            } else if(rbperempuan.isSelected()){
                jeniskelamin = rbperempuan.getText();
            } else {
                jeniskelamin = "";
            }
        String notelp = txtnotelp.getText();
        String email = txtemail.getText();
        String jurusan = cbjurusan.getSelectedItem().toString();
        String kelas = cbkelas.getSelectedItem().toString();
        
        if(nis.isEmpty()||namasiswa.isEmpty()||ttl.isEmpty()||jeniskelamin.isEmpty()||notelp.isEmpty()||email.isEmpty()||jurusan.isEmpty()||kelas.isEmpty()){
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !","Validasi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "update DataSiswa set Nama_Siswa = ?,Tempat_Tanggal_Lahir = ?,Jenis_Kelamin = ?,No_Telp = ?,Email = ?,Jurusan = ?,Kelas = ? where NIS = ?";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, namasiswa);
                st.setString(2, ttl);
                st.setString(3, jeniskelamin);
                st.setString(4, notelp);
                st.setString(5, email);
                st.setString(6, jurusan);
                st.setString(7, kelas);
                st.setString(8, nis);
                
                int rowUpdated = st.executeUpdate();
                if(rowUpdated > 0) {
                    JOptionPane.showMessageDialog(this,"Data Berhasil Diperbarui");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (Exception e){
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void deleteData() {
        int selectedRow = tbldatasiswa.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda Yakin Ingin Menghapus Data Ini?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            String nis = tbldatasiswa.getValueAt(selectedRow, 0).toString();
            try {
                String sql = "delete from DataSiswa where NIS=?";
                try(PreparedStatement st = conn.prepareStatement(sql)){
                    st.setString(1, nis);
                    int rowDeleted = st.executeUpdate();
                    if(rowDeleted > 0) {
                        JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus");
                    } else{
                        JOptionPane.showMessageDialog(this,"Data Gagal Dihapus");
                    }
                } 
            } catch (Exception e){
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE,null, e);
            }
        }
        resetForm();
        loadData();
        showPanel();
    }

    private void searchData() {
        String kataKunci = txtsearch.getText();
        
        DefaultTableModel model = (DefaultTableModel) tbldatasiswa.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "Select *from DataSiswa where NIS LIKE ? OR Nama_Siswa LIKE ? ";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, "%" + kataKunci + "%");
                st.setString(2, "%" + kataKunci + "%");
                ResultSet rs = st.executeQuery();
                
                while (rs.next()){
                    String nis = rs.getString("NIS");
                    String namasiswa = rs.getString("Nama_Siswa");
                    String ttl = rs.getString("Tempat_Tanggal_Lahir");
                    String jeniskelamin = rs.getString("Jenis_Kelamin");
                    String notelp = rs.getString("No_Telp");
                    String email = rs.getString("Email");
                    String jurusan = rs.getString("Jurusan");
                    String kelas = rs.getString("Kelas");
                    
                    Object[] rowData = {nis,namasiswa,ttl,jeniskelamin,notelp,email,jurusan,kelas};
                    model.addRow(rowData);
                }
            }
        }catch (Exception e) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE,null, e);
        }
    }
}
