import Config.Koneksi;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author firza
 */
public class DataJadwal extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    private final Connection conn;
    public DataJadwal() {
        initComponents();
        
        conn = Koneksi.getConnection();
        setTabelModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmain = new javax.swing.JPanel();
        datajadwal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatajadwal = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        btnubah = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tambahdatajadwal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtidjadwal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbjurusan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbkelas = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbmapel = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbhari = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtjam = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        panelmain.setBackground(new java.awt.Color(255, 255, 255));
        panelmain.setLayout(new java.awt.CardLayout());

        datajadwal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Master Data > Data Jadwal");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tv-20.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data Jadwal ");

        tbldatajadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbldatajadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldatajadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldatajadwal);

        btntambah.setBackground(new java.awt.Color(102, 102, 255));
        btntambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 0, 0));
        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(255, 153, 0));
        btnbatal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 102, 102));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });

        btnubah.setBackground(new java.awt.Color(102, 102, 255));
        btnubah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-20.png"))); // NOI18N

        javax.swing.GroupLayout datajadwalLayout = new javax.swing.GroupLayout(datajadwal);
        datajadwal.setLayout(datajadwalLayout);
        datajadwalLayout.setHorizontalGroup(
            datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datajadwalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, datajadwalLayout.createSequentialGroup()
                        .addGroup(datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(datajadwalLayout.createSequentialGroup()
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                        .addGroup(datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datajadwalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datajadwalLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        datajadwalLayout.setVerticalGroup(
            datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datajadwalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelmain.add(datajadwal, "card2");

        tambahdatajadwal.setBackground(new java.awt.Color(255, 255, 255));
        tambahdatajadwal.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Master Data > Data Jadwal > Tambah Data");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tv-20.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Tambah Data Jadwal ");

        btnsimpan.setBackground(new java.awt.Color(102, 102, 255));
        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(255, 153, 0));
        btncancel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btncancel.setText("BATAL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Id Jadwal");

        txtidjadwal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtidjadwal.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nama Guru");

        txtnama.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(51, 51, 51));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Jurusan");

        cbjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Item--", "Akuntansi", "Teknologi Komputer Jaringan", "Otomatisasi dan Tata Kelola Perkantoran" }));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Kelas");

        cbkelas.setForeground(new java.awt.Color(51, 51, 51));
        cbkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Item--", "X", "XI", "XII" }));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Mata Pelajaran");

        cbmapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Item--", "Akuntansi Keuangan", "Bahasa Inggris", "Bahasa Indonesia", "Matematika", "PPKN", "Kewirausahaan", "Komputer Akuntansi", "Ak Pemerintah", "Ak Manufaktur", "Pajak", "Pai", " " }));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Hari");

        cbhari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Item--", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu" }));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Jam");

        txtjam.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtjam.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout tambahdatajadwalLayout = new javax.swing.GroupLayout(tambahdatajadwal);
        tambahdatajadwal.setLayout(tambahdatajadwalLayout);
        tambahdatajadwalLayout.setHorizontalGroup(
            tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdatajadwalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahdatajadwalLayout.createSequentialGroup()
                        .addGroup(tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahdatajadwalLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 597, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addGroup(tambahdatajadwalLayout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(tambahdatajadwalLayout.createSequentialGroup()
                        .addGroup(tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambahdatajadwalLayout.createSequentialGroup()
                        .addGroup(tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(cbhari, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15)
                            .addComponent(cbmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(cbjurusan, 0, 443, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)
                                .addComponent(txtnama)
                                .addComponent(cbkelas, 0, 443, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        tambahdatajadwalLayout.setVerticalGroup(
            tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdatajadwalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(tambahdatajadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbhari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        panelmain.add(tambahdatajadwal, "card2");

        add(panelmain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(btnsimpan.getText().equals("TAMBAH")){
            btnsimpan.setText("SIMPAN");
        }
        else if(btnsimpan.getText().equals("SIMPAN")){
            insertData();
        }
        else if(btnsimpan.getText().equals("PERBARUI")){
            updateData();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        panelmain.removeAll();
        panelmain.add(tambahdatajadwal);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
        searchData();
    }//GEN-LAST:event_txtsearchKeyTyped

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        updateData();
        
        if(btnubah.getText().equals("UBAH")){
            dataTabel();
            btnsimpan.setText("PERBARUI");
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void tbldatajadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldatajadwalMouseClicked
        if(btntambah.getText().equals("TAMBAH")){
            btnubah.setVisible(true);
            btnhapus.setVisible(true);
            btnbatal.setVisible(true);
        }
    }//GEN-LAST:event_tbldatajadwalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbhari;
    private javax.swing.JComboBox<String> cbjurusan;
    private javax.swing.JComboBox<String> cbkelas;
    private javax.swing.JComboBox<String> cbmapel;
    private javax.swing.JPanel datajadwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPanel tambahdatajadwal;
    private javax.swing.JTable tbldatajadwal;
    private javax.swing.JTextField txtidjadwal;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        getData((DefaultTableModel) tbldatajadwal.getModel());
        }
    
    private void showPanel(){
        panelmain.removeAll();
        panelmain.add(new DataJadwal());
        panelmain.repaint();
        panelmain.revalidate();
    }
    
    private void resetForm() {
        txtidjadwal.setText("");
        txtnama.setText("");
        cbjurusan.setSelectedItem(0);
        cbkelas.setSelectedItem(0);
        cbmapel.setSelectedItem(0);
        txtjam.setText("");
    }

    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tbldatajadwal.getModel();
        model.addColumn("Id Jadwal");
        model.addColumn("Nama Guru");
        model.addColumn("Mata Pelajaran");
        model.addColumn("Jurusan");
        model.addColumn("Kelas");
        model.addColumn("Hari");
        model.addColumn("Jam");
    }
    
    private void getData(DefaultTableModel model){
        model.setRowCount(0);
        
        try {
            String sql = "Select *from Jadwal";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                
                while (rs.next()){
                    String idjadwal = rs.getString("Id_Jadwal");
                    String namaguru = rs.getString("Nama_Guru");
                    String namamapel = rs.getString("Nama_Mapel");
                    String jurusan = rs.getString("Jurusan");
                    String kelas = rs.getString("Kelas");
                    String hari = rs.getString("Hari");
                    String waktu = rs.getString("Jam");
                    
                    Object[] rowData = {idjadwal,namaguru,namamapel,jurusan,kelas,hari,waktu};
                    model.addRow(rowData);
                }
            }
        }catch (Exception e) {
            Logger.getLogger(DataJadwal.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void insertData() {
        String idjadwal = txtidjadwal.getText();
        String namaguru = txtnama.getText();
        String mapel = cbmapel.getSelectedItem().toString();
        String jurusan = cbjurusan.getSelectedItem().toString();
        String kelas = cbkelas.getSelectedItem().toString();
        String hari = cbhari.getSelectedItem().toString();
        String waktu = txtjam.getText();
        
        if(idjadwal.isEmpty()||namaguru.isEmpty()||mapel.isEmpty()||jurusan.isEmpty()||kelas.isEmpty()||hari.isEmpty()||waktu.isEmpty()){
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !","Validasi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "insert into jadwal(Id_Jadwal,Nama_Guru,Nama_Mapel,Jenis_Kelamin,Jurusan,Kelas,Hari,Jam) values (?,?,?,?,?,?,?)";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, idjadwal);
                st.setString(2, namaguru);
                st.setString(3, mapel);
                st.setString(4, jurusan);
                st.setString(5, kelas);
                st.setString(6, hari);
                st.setString(7, waktu);
                
                int rowInserted = st.executeUpdate();
                if(rowInserted > 0) {
                    JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (Exception e){
            Logger.getLogger(DataJadwal.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void dataTabel() {
        datajadwal.setVisible(false);
        tambahdatajadwal.setVisible(true);
        
        int row = tbldatajadwal.getSelectedRow();
        jLabel6.setText("Perbarui Data Jadwal");
        jLabel4.setText("Master Data > Data Jadwal > Perbarui Data");
        
        txtidjadwal.setText(tbldatajadwal.getValueAt(row,0).toString());
        txtnama.setText(tbldatajadwal.getValueAt(row,1).toString());
        cbmapel.setSelectedItem (tbldatajadwal.getValueAt(row,2).toString());
        cbjurusan.setSelectedItem (tbldatajadwal.getValueAt(row,3).toString());
        cbkelas.setSelectedItem (tbldatajadwal.getValueAt(row,4).toString());
        cbhari.setSelectedItem (tbldatajadwal.getValueAt(row,5).toString());
        txtjam.setText(tbldatajadwal.getValueAt(row,6).toString());
    }
    
    private void updateData() {
        String idjadwal = txtidjadwal.getText();
        String namaguru = txtnama.getText();
        String mapel = cbmapel.getSelectedItem().toString();
        String jurusan = cbjurusan.getSelectedItem().toString();
        String kelas = cbkelas.getSelectedItem().toString();
        String hari = cbhari.getSelectedItem().toString();
        String waktu = txtjam.getText();
        
        if(idjadwal.isEmpty()||namaguru.isEmpty()||mapel.isEmpty()||jurusan.isEmpty()||kelas.isEmpty()||hari.isEmpty()||waktu.isEmpty()){
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !","Validasi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "update jadwal set Nama_Guru = ?,Nama_Mapel = ?,Jurusan = ?,Kelas = ? ,Hari = ?,Jam = ? where Id_Jadwal = ?";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, namaguru);
                st.setString(2, mapel);
                st.setString(3, jurusan);
                st.setString(4, kelas);
                st.setString(5, hari);
                st.setString(6, waktu);
                st.setString(7, idjadwal);
                
                int rowUpdated = st.executeUpdate();
                if(rowUpdated > 0) {
                    JOptionPane.showMessageDialog(this,"Data Berhasil Diperbarui");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (Exception e){
            Logger.getLogger(DataJadwal.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void deleteData() {
        int selectedRow = tbldatajadwal.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda Yakin Ingin Menghapus Data Ini?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            String nis = tbldatajadwal.getValueAt(selectedRow, 0).toString();
            try {
                String sql = "delete from Jadwal where Id_Jadwal=?";
                try(PreparedStatement st = conn.prepareStatement(sql)){
                    st.setString(1, nis);
                    int rowDeleted = st.executeUpdate();
                    if(rowDeleted > 0) {
                        JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus");
                    } else{
                        JOptionPane.showMessageDialog(this,"Data Gagal Dihapus");
                    }
                } 
            } catch (Exception e){
            Logger.getLogger(DataJadwal.class.getName()).log(Level.SEVERE,null, e);
            }
        }
        resetForm();
        loadData();
        showPanel();
    }

    private void searchData() {
        String kataKunci = txtsearch.getText();
        
        DefaultTableModel model = (DefaultTableModel) tbldatajadwal.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "Select *from Jadwal where Id_Jadwal LIKE ? OR Nama_Guru LIKE ? OR Nama_Mapel LIKE ?";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, "%" + kataKunci + "%");
                st.setString(2, "%" + kataKunci + "%");
                st.setString(3, "%" + kataKunci + "%");
                ResultSet rs = st.executeQuery();
                
                while (rs.next()){
                    String idjadwal = rs.getString("Id_Jadwal");
                    String namaguru = rs.getString("Nama_Guru");
                    String namamapel = rs.getString("Nama_Mapel");
                    String jurusan = rs.getString("Jurusan");
                    String kelas = rs.getString("Kelas");
                    String hari = rs.getString("Hari");
                    String waktu = rs.getString("Jam");
                    
                    Object[] rowData = {idjadwal,namaguru,namamapel,jurusan,kelas,hari,waktu};
                    model.addRow(rowData);
                }
            }
        }catch (Exception e) {
            Logger.getLogger(DataJadwal.class.getName()).log(Level.SEVERE,null, e);
        }
    }
}
