import Config.Koneksi;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author firza
 */
public class DataGuru extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    private final Connection conn;
    public DataGuru() {
        initComponents();
        
        conn = Koneksi.getConnection();
        setTabelModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJK = new javax.swing.ButtonGroup();
        panelmain = new javax.swing.JPanel();
        dataguru = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldataguru = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        btnubah = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tambahdataguru = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtnip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbmapel = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtnotelp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();

        setLayout(new java.awt.CardLayout());

        panelmain.setBackground(new java.awt.Color(255, 255, 255));
        panelmain.setLayout(new java.awt.CardLayout());

        dataguru.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Master Data > Data Guru");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tv-20.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data Guru ");

        tbldataguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbldataguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataguruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldataguru);

        btntambah.setBackground(new java.awt.Color(102, 102, 255));
        btntambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 0, 0));
        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(255, 153, 0));
        btnbatal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 102, 102));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });

        btnubah.setBackground(new java.awt.Color(102, 102, 255));
        btnubah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-20.png"))); // NOI18N

        javax.swing.GroupLayout dataguruLayout = new javax.swing.GroupLayout(dataguru);
        dataguru.setLayout(dataguruLayout);
        dataguruLayout.setHorizontalGroup(
            dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataguruLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataguruLayout.createSequentialGroup()
                        .addGroup(dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(dataguruLayout.createSequentialGroup()
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                        .addGroup(dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataguruLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataguruLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        dataguruLayout.setVerticalGroup(
            dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataguruLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelmain.add(dataguru, "card2");

        tambahdataguru.setBackground(new java.awt.Color(255, 255, 255));
        tambahdataguru.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Master Data > Data Guru > Tambah Data");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tv-20.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Tambah Data Guru");

        btnsimpan.setBackground(new java.awt.Color(102, 102, 255));
        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(255, 153, 0));
        btncancel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btncancel.setText("BATAL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("NIP");

        txtnip.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnip.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nama Guru");

        txtnama.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(51, 51, 51));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Mata Pelajaran");

        cbmapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Item--", "Akuntansi Keuangan", "Bahasa Inggris", "Bahasa Indonesia", "Matematika", "PPKN", "Kewirausahaan", "Komputer Akuntansi", "Ak Pemerintah", "Ak Manufaktur", "Pajak", "Pai" }));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("No Telp");

        txtnotelp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnotelp.setForeground(new java.awt.Color(51, 51, 51));
        txtnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotelpActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Email");

        txtemail.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtemail.setForeground(new java.awt.Color(51, 51, 51));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Jenis Kelamin");

        rbJK.add(rblaki);
        rblaki.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        rblaki.setForeground(new java.awt.Color(51, 51, 51));
        rblaki.setText("Laki-laki");

        rbJK.add(rbperempuan);
        rbperempuan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        rbperempuan.setForeground(new java.awt.Color(51, 51, 51));
        rbperempuan.setText("Perempuan");
        rbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbperempuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahdataguruLayout = new javax.swing.GroupLayout(tambahdataguru);
        tambahdataguru.setLayout(tambahdataguruLayout);
        tambahdataguruLayout.setHorizontalGroup(
            tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdataguruLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahdataguruLayout.createSequentialGroup()
                        .addGroup(tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahdataguruLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 633, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addGroup(tambahdataguruLayout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(tambahdataguruLayout.createSequentialGroup()
                        .addGroup(tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambahdataguruLayout.createSequentialGroup()
                        .addGroup(tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(cbmapel, 0, 443, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel8)
                                .addComponent(txtnama)
                                .addComponent(txtnotelp)
                                .addComponent(txtemail))
                            .addGroup(tambahdataguruLayout.createSequentialGroup()
                                .addComponent(rblaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbperempuan)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        tambahdataguruLayout.setVerticalGroup(
            tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahdataguruLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahdataguruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rblaki)
                    .addComponent(rbperempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        panelmain.add(tambahdataguru, "card2");

        add(panelmain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(btnsimpan.getText().equals("TAMBAH")){
            btnsimpan.setText("SIMPAN");
        }
        else if(btnsimpan.getText().equals("SIMPAN")){
            insertData();
        }
        else if(btnsimpan.getText().equals("PERBARUI")){
            updateData();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        panelmain.removeAll();
        panelmain.add(tambahdataguru);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotelpActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void rbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbperempuanActionPerformed

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
        searchData();
    }//GEN-LAST:event_txtsearchKeyTyped

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        updateData();
        
        if(btnubah.getText().equals("UBAH")){
            dataTabel();
            btnsimpan.setText("PERBARUI");
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void tbldataguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataguruMouseClicked
        if(btntambah.getText().equals("TAMBAH")){
            btnubah.setVisible(true);
            btnhapus.setVisible(true);
            btnbatal.setVisible(true);
        }
    }//GEN-LAST:event_tbldataguruMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbmapel;
    private javax.swing.JPanel dataguru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelmain;
    private javax.swing.ButtonGroup rbJK;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JPanel tambahdataguru;
    private javax.swing.JTable tbldataguru;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        getData((DefaultTableModel) tbldataguru.getModel());
        }
    
    private void showPanel(){
        panelmain.removeAll();
        panelmain.add(new DataGuru());
        panelmain.repaint();
        panelmain.revalidate();
    }
    
    private void resetForm() {
        txtnip.setText("");
        txtnama.setText("");
        rbJK.clearSelection();
        txtnotelp.setText("");
        txtemail.setText("");
        cbmapel.setSelectedItem(0);
    }

    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tbldataguru.getModel();
        model.addColumn("NIP");
        model.addColumn("Nama Guru");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No Telp");
        model.addColumn("Email");
        model.addColumn("Mata Pelajaran");
    }
    
    private void getData(DefaultTableModel model){
        model.setRowCount(0);
        
        try {
            String sql = "Select *from DataGuru";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                
                while (rs.next()){
                    String nip = rs.getString("NIP");
                    String namaguru = rs.getString("Nama_Guru");
                    String jeniskelamin = rs.getString("Jenis_Kelamin");
                    String notelp = rs.getString("No_Telp");
                    String email = rs.getString("Email");
                    String mapel = rs.getString("Nama_Mapel");
                    
                    Object[] rowData = {nip,namaguru,jeniskelamin,notelp,email,mapel};
                    model.addRow(rowData);
                }
            }
        }catch (Exception e) {
            Logger.getLogger(DataGuru.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void insertData() {
        String nip = txtnip.getText();
        String namaguru = txtnama.getText();
        String jeniskelamin;
            if(rblaki.isSelected()){
                
                jeniskelamin = rblaki.getText();
            } else if(rbperempuan.isSelected()){
                jeniskelamin = rbperempuan.getText();
            } else {
                jeniskelamin = "";
            }
        String notelp = txtnotelp.getText();
        String email = txtemail.getText();
        String mapel = cbmapel.getSelectedItem().toString();
        
        if(nip.isEmpty()||namaguru.isEmpty()||jeniskelamin.isEmpty()||notelp.isEmpty()||email.isEmpty()||mapel.isEmpty()){
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !","Validasi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "insert into DataGuru(NIP,Nama_Guru,Jenis_Kelamin,No_Telp,Email,Nama_Mapel) values (?,?,?,?,?,?)";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, nip);
                st.setString(2, namaguru);
                st.setString(3, jeniskelamin);
                st.setString(4, notelp);
                st.setString(5, email);
                st.setString(6, mapel);
                
                int rowInserted = st.executeUpdate();
                if(rowInserted > 0) {
                    JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan");
                    resetForm();
                    loadData();
                    showPanel();
                }
            }
        } catch (Exception e){
            Logger.getLogger(DataGuru.class.getName()).log(Level.SEVERE,null, e);
        }
    }

    private void dataTabel() {
        dataguru.setVisible(false);
        tambahdataguru.setVisible(true);
        
        int row = tbldataguru.getSelectedRow();
        jLabel6.setText("Perbarui Data Guru");
        jLabel4.setText("Master Data > Data Guru > Perbarui Data");
        
        txtnip.setText(tbldataguru.getValueAt(row,0).toString());
        txtnama.setText(tbldataguru.getValueAt(row,1).toString());
        String jeniskelamin = tbldataguru.getValueAt(row,2).toString();
            if(jeniskelamin.equals("Laki-laki")){
                rblaki.setSelected(true);
            } else if(jeniskelamin.equals("Perempuan")){
                rbperempuan.setSelected(true);
            }
        txtnotelp.setText(tbldataguru.getValueAt(row,3).toString());
        txtemail.setText(tbldataguru.getValueAt(row,4).toString());
        cbmapel.setSelectedItem (tbldataguru.getValueAt(row,5).toString());
    }
    
    private void updateData() {
    String nip = txtnip.getText();
    String namaguru = txtnama.getText();
    String jeniskelamin;
    if(rblaki.isSelected()){
        jeniskelamin = rblaki.getText();
    } else if(rbperempuan.isSelected()){
        jeniskelamin = rbperempuan.getText();
    } else {
        jeniskelamin = "";
    }
    String notelp = txtnotelp.getText();
    String email = txtemail.getText();
    String mapel = cbmapel.getSelectedItem().toString();

    if(nip.isEmpty()||namaguru.isEmpty()||jeniskelamin.isEmpty()||notelp.isEmpty()||email.isEmpty()||mapel.isEmpty()){
        JOptionPane.showMessageDialog(this,"Semua kolom harus diisi !","Validasi",JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        String sql = "UPDATE DataGuru SET Nama_Guru = ?, Jenis_Kelamin = ?, No_Telp = ?, Email = ?, Nama_Mapel = ? WHERE NIP = ?";
        try(PreparedStatement st = conn.prepareStatement(sql)){
            st.setString(1, namaguru);
            st.setString(2, jeniskelamin);
            st.setString(3, notelp);
            st.setString(4, email);
            st.setString(5, mapel);
            st.setString(6, nip);

            int rowUpdated = st.executeUpdate();
            if(rowUpdated > 0) {
                JOptionPane.showMessageDialog(this,"Data Berhasil Diperbarui");
                resetForm();
                loadData();
                showPanel();
            }
        }
    } catch (Exception e){
        Logger.getLogger(DataGuru.class.getName()).log(Level.SEVERE,null, e);
    }
}

    private void deleteData() {
        int selectedRow = tbldataguru.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda Yakin Ingin Menghapus Data Ini?",
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            String nip = tbldataguru.getValueAt(selectedRow, 0).toString();
            try {
                String sql = "delete from DataGuru where NIP=?";
                try(PreparedStatement st = conn.prepareStatement(sql)){
                    st.setString(1, nip);
                    int rowDeleted = st.executeUpdate();
                    if(rowDeleted > 0) {
                        JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus");
                    } else{
                        JOptionPane.showMessageDialog(this,"Data Gagal Dihapus");
                    }
                } 
            } catch (Exception e){
            Logger.getLogger(DataGuru.class.getName()).log(Level.SEVERE,null, e);
            }
        }
        resetForm();
        loadData();
        showPanel();
    }

    private void searchData() {
        String kataKunci = txtsearch.getText();
        
        DefaultTableModel model = (DefaultTableModel) tbldataguru.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "Select *from DataGuru where NIP LIKE ? OR Nama_Guru LIKE ? ";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, "%" + kataKunci + "%");
                st.setString(2, "%" + kataKunci + "%");
                ResultSet rs = st.executeQuery();
                
                while (rs.next()){
                    String nip = rs.getString("NIP");
                    String namaguru = rs.getString("Nama_Guru");
                    String jeniskelamin = rs.getString("Jenis_Kelamin");
                    String notelp = rs.getString("No_Telp");
                    String email = rs.getString("Email");
                    String mapel = rs.getString("Nama_Mapel");
                    
                    Object[] rowData = {nip,namaguru,jeniskelamin,notelp,email,mapel};
                    model.addRow(rowData);
                }
            }
        }catch (Exception e) {
            Logger.getLogger(DataGuru.class.getName()).log(Level.SEVERE,null, e);
        }
    }
}
